name: wellium_flutter_app
description: A Flutter app for managing health data with SSO authentication and local data persistence.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.3.6

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # SSO Integration (Choose based on your SSO provider)
  flutter_appauth: ^8.0.3 # Example for OAuth2-based SSO
  http: ^1.3.0

  # Dependency Injection
  # Not needed explicitly as Riverpod handles it

  # UI and Theming
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.3.6

  # Animations
  animations: ^2.0.6

  # Logging
  sentry_flutter: ^8.12.0
  logger: ^2.5.0

  # Security
  flutter_secure_storage: ^10.0.0-beta.4

  # Other utilities
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  mocktail: ^1.0.4
  freezed: ^2.3.2
  freezed_annotation: ^2.3.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: CodeNewRoman
      fonts:
        - asset: assets/fonts/CodeNewRoman-Regular.otf
        - asset: assets/fonts/CodeNewRoman-Bold.otf
          weight: 700
