# .github/ISSUE_TEMPLATE/bug_report.yml
name: Bug report
description: Report a reproducible bug in wellium
title: "[BUG] <short summary>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve wellium. Please do not include personal health data.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS and version (e.g., Android 14, iOS 17, Windows 11, macOS 14, Ubuntu 24.04)
      placeholder: OS and version
    validations:
      required: true

  - type: input
    id: versions
    attributes:
      label: App and CLI versions
      description: wellium app version; Ionic CLI version from `ionic --version`
      placeholder: wellium 0.x.y; Ionic CLI x.y.z
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List the actions that trigger the bug.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Logs, screenshots, or notes (redact any personal data).
      placeholder: Paste logs or drag images here.

  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy check
      description: Confirm you removed any personal or clinical data.
      options:
        - label: I confirm this report contains no personal or clinical data.
          required: true
