# .github/ISSUE_TEMPLATE/feature_request.yml
name: Feature request
description: Propose a new feature or enhancement for wellium
title: "[FEATURE] <short summary>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping shape wellium. Focus on how this improves the single source of truth and collaboration with providers.

  - type: input
    id: summary
    attributes:
      label: Brief summary
      description: One sentence overview of the feature
      placeholder: Add support for ...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: User need or motivation
      description: Why do patients or providers need this?
      placeholder: Describe the problem this solves.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How would this work? Include any technical details.
      placeholder: Outline UI flow, data model, and any APIs.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other options you evaluated
      placeholder: List pros and cons.

  - type: dropdown
    id: alignment
    attributes:
      label: Alignment
      description: Select all that apply.
      multiple: true
      options:
        - Strengthens a person-centered single source of truth for health data.
        - Improves collaboration with clinicians, caregivers, or other trusted partners.
        - Strengthens a person-centered single source of truth for health data and improves collaboration with clinicians, caregivers, or other trusted partners.
    validations:
      required: true

  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy check
      options:
        - label: I confirm this request contains no personal or clinical data.
          required: true
